### ISSUE TITLE
code run issue

### ISSUE THREAD

**Issue by lwind18** [DPIRD-DMA/CloudS2Mask#1]
Hey when I use the model,
at: scene_settings = create_settings(
    sent_safe_dirs=l1c_folders,
    output_dir=output_dir,
    processing_res=20,
) step, some error happend:
File "/opt/conda/envs/user/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ConvNormAct' object has no attribute 'aa'
I am using Linux system.
In order to run the code, do I need to install torch? It looks like you are using torch package.

**Comment by wrignj08** [comment]
Thanks for letting me know, it looks like this is the result of the models being built with an older version of the timm library and trying to load them with a newer version. 
You can fix this by specifying an older version of the timm library like this.

pip install timm===0.9.10

I will push an update with specifies this dependancy.

**Comment by wrignj08** [comment]
I have just pushed the fix as version 1.1.3 and validated this to work in colab, you can grab the new version like this 

pip install clouds2mask==1.1.3

**Comment by lwind18** [comment]
Thank you for quick response.
I installed 1.1.3 and it is working now!
