### ISSUE TITLE
Packages requirements

### ISSUE THREAD

**Issue by Endmember** [DPIRD-DMA/CloudS2Mask#2]
I am very grateful to the authors for their hard work in remote sensing cloud detection research and for providing convenient public code. When using it, I found that the installation of the library actually has strict version dependencies. For example, fastai 2.7 and above are required packages for the CloudS2Mask library, but it seems that it cannot be installed in lower versions of python, which caused me to spend a lot of time testing conda, pip, and python versions. In the end, I found that python3.9 and above seem to be suitable. In addition, CloudS2Mask also forces the installation of pytorch and CUDA-related dependent libraries, which may destroy the built cuda and pytorch environment because different graphics card drivers and cuda use different pytorch versions. Therefore, I hope that the author can describe the requirements of the CloudS2Mask library in detail, and consider allowing users to install pytorch and other libraries suitable for local drivers by themselves.

**Comment by wrignj08** [comment]
Hi! Thanks for your detailed feedback about the installation issues.

I'll update the README to include:

- The required Python version (>=3.9)
- Recommended environment setup steps to make the installation process smoother

Regarding the PyTorch and CUDA dependencies - these are actually managed by FastAI, which is a core requirement for our library. We don't have direct control over FastAI's dependency management. If you have suggestions for handling this better, I'm definitely open to hearing them!

Thanks for bringing this to our attention and helping us improve the documentation.

**Comment by Endmember** [comment]
> 您好！感谢您就安装问题提供详细的反馈。
> 
> 我将更新 README 以包含以下内容：
> 
> * 所需的 Python 版本（>=3.9）
> * 推荐的环境设置步骤，让安装过程更顺畅
> 
> 关于 PyTorch 和 CUDA 依赖项 - 这些实际上由 FastAI 管理，这是我们库的核心要求。我们无法直接控制 FastAI 的依赖项管理。如果您有更好地处理此问题的建议，我绝对愿意听取！
> 
> 感谢您提请我们注意这一点并帮助我们改进文档。

Thank you for your prompt reply. For the FASTAI package, there is indeed a dependency on a specific version. For this, I can only think of specifying the version of pytorch from the installation, for example, for CUDA11.3: `pip install clouds2mask torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113`, or more securely reinstall the torch corresponding to the local CUDA version after clouds2mask. Of course, for users who use an earlier CUDA version, the local torch, torchvision, and torchaudio may not just meet the requirements of FASTAI>=2.7. From the official website, CUDA versions are generally suitable above 10.2 and 11.3. You can verify it and it is recommended that you provide a prompt for the CUDA version.

**Comment by Endmember** [comment]
> Hi! Thanks for your detailed feedback about the installation issues.
> 
> I'll update the README to include:
> 
> * The required Python version (>=3.9)
> * Recommended environment setup steps to make the installation process smoother
> 
> Regarding the PyTorch and CUDA dependencies - these are actually managed by FastAI, which is a core requirement for our library. We don't have direct control over FastAI's dependency management. If you have suggestions for handling this better, I'm definitely open to hearing them!
> 
> Thanks for bringing this to our attention and helping us improve the documentation.

Thanks for your prompt reply. For the FASTAI package, there is indeed a dependency on a specific version. For this, I can only think of specifying the version of pytorch from the installation, for example, for CUDA11.3: `pip install clouds2mask torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113`, or more securely reinstall the torch corresponding to the local CUDA version after clouds2mask. Of course, for users who use an earlier CUDA version, the local torch, torchvision, and torchaudio may not just meet the requirements of FASTAI>=2.7. From the official website, CUDA versions are generally suitable above 10.2 and 11.3. You can verify it and it is recommended that you provide a prompt for the CUDA version.

**Comment by Endmember** [comment]
An additional suggestion is to prompt users to cite "Wright N, Duncan J M A, Callow J N, et al. CloudS2Mask: A novel deep learning approach for improved cloud and cloud shadow masking in Sentinel-2 imagery[J]. Remote Sensing of Environment, 2024, 306: 114122." when using CloudS2Mask or OmniCloudMask.

**Comment by wrignj08** [comment]
Thanks for your suggestions, for now I have added a link to the CloudS2Mask paper and citation details to the README.
